VERSIONS=(4.8)
VARIANTS=(nano)

build:
	for %%V in $(VERSIONS); do \
		for %%X in $(VARIANTS); do \
			make -C %%V/%%X \
			-e TASQUE_VERSION=$(TASQUE_VERSION) \
			-e LANGUAGE=$(LANGUAGE) \
			-e VERSION=%%V \
			-e VARIANT=%%X

push:
	for %%V in $(VERSIONS); do \
		for %%X in $(VARIANTS); do \
			make push -C %%V/%%X \
			-e TASQUE_VERSION=$(TASQUE_VERSION) \
			-e LANGUAGE=$(LANGUAGE) \
			-e VERSION=%%V \
			-e VARIANT=%%X