TASQUE_VERSION=0.02
LANGUAGES=(node)

build:
	for %%L in $(LANGUAGES); do \
		make -C %%L \
		-e TASQUE_VERSION=$(TASQUE_VERSION) \
		-e LANGUAGE=%%L

push: build
	for %%L in $(LANGUAGES); do \
		make push -C %%L \
		-e TASQUE_VERSION=$(TASQUE_VERSION) \
		-e LANGUAGE=%%L
